### ISSUE TITLE
Feature: Configurable extra log message to display with every log

### ISSUE THREAD

**Issue by hiro5id** [hiro5id/console-log-json#10]

**Comment by rkristelijn** [comment]
This is a feature that I would like to have; I'm unsure if this matches the feature description and ideas @hiro5id has;

## Current situation

When you want to have additional stuff included in every log, e.g. some statics, like application-name, client, owner, ... you need to provide these with every log:

I now created a function that returns these statics so I can just include them, the logDefaults returns an object: 

```json
{
  "application": "my-application",
  "client": "facebook",
  "owner": "Leeroy Jenkins"
}
```

```typescript
import { LoggerAdaptToConsole } from 'console-log-json';
import { logDefaults } from './log.defaults';

export const startLogger = (): void => {
  if (process.env.LOG_FORMAT === 'text') {
    console.log('Logging format is text', logDefaults('startLogger'));
  } else {
    LoggerAdaptToConsole();
    console.log('Logging format is json', logDefaults('startLogger'));
  }
};
```

## Desired:

when bootstrapping, these values can be provided in the ` LoggerAdaptToConsole()`:

```
import { LoggerAdaptToConsole } from 'console-log-json';

 LoggerAdaptToConsole({
  "application": "my-application",
  "stuff": "from the thing"
});
 ```

**Comment by hiro5id** [comment]
Great idea.


I'll have to take a deeper look.  I'm just a bit overwhelmed with life, my daughter in the hospital.  But I would gladly welcome pull requests. 😊 Otherwise it will have to wait until I can free up some bandwidth 🙏

**Comment by rkristelijn** [comment]
Thanks for the prompt reply. I'm sorry to hear that. I hope she is on the mend soon. Next week we will look at creating a pull request.

**Comment by rkristelijn** [comment]
Hi @hiro5id I've created a draft PR. Is this the direction you want to move in?

**Comment by rkristelijn** [comment]
@hiro5id, I removed WIP status, would you accept this merge request?

Thanks @Syctorius for the help with the test

**Comment by hiro5id** [comment]
Thanks @Syctorius and @rkristelijn you are awesome.  I'll take a look and merge as soon as I can. This is great.  I'll make sure you're added to contributors list as well.

**Comment by hiro5id** [comment]
@all-contributors please add @rkristelijn for code

**Comment by hiro5id** [comment]
OK.. published to npm: https://www.npmjs.com/package/console-log-json as v3.1.1
