### ISSUE TITLE
colorized formatted json for easier reading when running locally

### ISSUE THREAD

**Issue by hiro5id** [hiro5id/console-log-json#17]

**Comment by johhnsmmith198** [comment]
Fantastic library @hiro5id , I use it on all my projects! Thanks a lot.
please can you prioritise this work though? It's so difficult to read locally

**Comment by johhnsmmith198** [comment]
wondering if you could allow a wrapper function that can be defined in the user config.
Then the user could define a function that color the output like this one for instance: https://www.npmjs.com/package/json-colorizer

**Comment by johhnsmmith198** [comment]
actually winston has a color capability I think: https://www.npmjs.com/package/winston

**Comment by johhnsmmith198** [comment]
I could do this as well to handle the coloring outside the nodejs process :
```
node src/index.js | jq -c
```

**Comment by hiro5id** [comment]
I admit this is something that bugs me me for local development too.  I'll need to look into this.  But I do have a day job that takes a lot of time, even so I would enjoy implementing this kind of thing.  However please know that if you can't wait, I am happy to accept a pull request.

**Comment by johhnsmmith198** [comment]
Hey @hiro5id , I can see you are back at it?
Are you considering this issue, please?

**Comment by hiro5id** [comment]
@johhnsmmith198 I have implemented colouring... starting [v2.12.0](https://www.npmjs.com/package/console-log-json/v/2.12.0) .  The existing colours are not customizable yet, but I plan on allowing custom configs in following versions...
