### ISSUE TITLE
Suggestion: Provide a way to remove the extra new line at the end of each line

### ISSUE THREAD

**Issue by SAPikachu** [hiro5id/console-log-json#40]
The extra new line results as an empty line in Google Cloud Log Explorer. `CONSOLE_LOG_JSON_NO_NEW_LINE_CHARACTERS` can turn this off, but I want to keep new lines inside stack traces.

![image](https://user-images.githubusercontent.com/653824/184047924-27f96e20-b396-46b3-babb-c60067e98130.png)

**Comment by hiro5id** [comment]
deployed in [v2.11.0](https://www.npmjs.com/package/console-log-json/v/2.11.0)
